export const services = [
    { number: '01', symbol: '↗', title: 'Assess what you’ve built.', description: 'Make a clear decision about what to keep, rebuild, or retire. Review the prototype alongside your workflows, data, and constraints, then prioritize what is worth taking to production.', deliverables: ['Prototype & workflow assessment', 'Prioritized path to production', 'Success measures & risk review'], tag: 'AI STRATEGY' },
    { number: '02', symbol: '⌘', title: 'Build it into the business.', description: 'Take the prototype to production. Connect it to the tools and information your team uses, and make agents, automations, and products dependable under real load.', deliverables: ['Custom agents & workflow automation', 'Knowledge systems & integrations', 'Interfaces built for your team'], tag: 'SYSTEMS & ENGINEERING' },
    { number: '03', symbol: '◎', title: 'Keep it moving.', description: 'Software is never finished. Stay on a subscription that covers maintenance, monitoring, and the next round of features, while your team learns to run it with confidence.', deliverables: ['Maintenance, monitoring & fixes', 'New features as your needs change', 'Team training & human oversight'], tag: 'ONGOING PARTNERSHIP' },
];
export const workflows = [
    { number: '01', title: 'Documents that move work forward.', category: 'OPERATIONS', before: 'People copy information between documents, spreadsheets, and business systems.', after: 'Extract and validate the key information, flag exceptions for review, and route it to the next step.', measure: 'Processing time · Rework · Exception rate' },
    { number: '02', title: 'Answers with the context behind them.', category: 'KNOWLEDGE', before: 'Teams search scattered files or wait for the one person who knows the answer.', after: 'Find answers across approved sources, with references and access controls that follow the user.', measure: 'Search time · Answer quality · Adoption' },
    { number: '03', title: 'Workflows with fewer loose ends.', category: 'ORCHESTRATION', before: 'Routine follow-ups and handoffs rely on someone remembering the next action.', after: 'Connect the steps, prepare the next action, and bring people in when a decision needs their judgment.', measure: 'Cycle time · Missed handoffs · Manual touches' },
];
export const steps = [
    { title: 'Understand', text: 'Start with what you have. Review the prototype and map the work around it with the people doing it, then find where it breaks against real data and real users.', output: 'A focused opportunity' },
    { title: 'Harden', text: 'Rebuild the core that matters. Test it with representative work and compare the result against a baseline before anything else gets built on top.', output: 'Evidence to move forward' },
    { title: 'Ship', text: 'Connect the system, handle exceptions, and give the team the controls and training they need to use it confidently.', output: 'A working capability' },
    { title: 'Evolve', text: 'Stay on it together. Track quality and usage, fix what breaks, and ship the next features as your needs change, on an ongoing subscription.', output: 'Software that keeps up' },
];
export const faqs = [
    { question: 'We already built something with AI. Can you take it from here?', answer: 'Yes, and it is the most common starting point. Share the prototype and where it falls short. We assess what is worth keeping, what needs rebuilding, and what it takes to connect it to your systems and run it reliably. From there we scope a focused build.' },
    { question: 'We know AI matters. Where do we start?', answer: 'Start with a recurring bottleneck: a slow process, repeated manual work, or information that is hard to use. Our first conversation is about that business problem. From there, we can scope an assessment or a focused pilot.' },
    { question: 'Do we need to replace our existing tools?', answer: 'Often, the useful work is connecting and extending what you already have. We assess your current systems first, then choose whether configuration, integration, or custom development makes the most sense.' },
    { question: 'How do you handle sensitive data and AI mistakes?', answer: 'We define data access, appropriate model use, evaluation criteria, and human review as part of the design. Higher-risk actions need stronger controls. The scope and safeguards depend on your information, systems, and operating requirements.' },
    { question: 'What does an engagement look like?', answer: 'We agree on a defined problem, deliverables, and success measures before starting. Work usually begins with a focused build to harden and ship what you have, then continues as an ongoing subscription for maintenance and new features. Timing and fees are scoped to the actual work.' },
];
