allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.2'
  - astro@7.0.2
onlyBuiltDependencies:
  - esbuild
  - sharp
packageExtensions:
  '@vercel/og@1.0.2':
    dependencies:
      harfbuzzjs: 0.10.0
patchedDependencies:
  '@vercel/og@1.0.2': patches/@vercel__og@1.0.2.patch
